### ISSUE TITLE
Issue with pip install ffmpeg-python - Code Still Crashes

### ISSUE THREAD

**Issue by Annie1ustc** [aiguo112/FFmpeg-Playground#1]
OS: Windows11
Python Version: 3.10
![image](https://github.com/aiguo112/FFmpeg-Playground/assets/7248059/90788c50-f6c4-418e-abb5-7f824e4a0e67)

**Comment by aiguo112** [comment]
[Download the latest ffmpeg for windows from this  link. ](https://github.com/BtbN/FFmpeg-Builds/releases)

Extract and paste the ffmpeg in your desired location and add the path in your variables list. 

You are good to go.
